diffusion_model_path: "hf://tristan-deep/semantic-diffusion-echo-dehazing"
segmentation_model_path: "hf://tristan-deep/semantic-segmentation-echo-dehazing"
seed: 42

params:
  diffusion_steps: 480
  initial_diffusion_step: 0
  batch_size: 16
  threshold_output_quantile: 0.17447
  preserve_bottom_percent: 32.0
  bottom_transition_width: 7.0

  mask_params:
    sigma: 4.2
    threshold: 0.176
  fixed_mask_params:
    top_px: 20
    bottom_px: 40
  skeleton_params:
    sigma_pre: 4.2
    sigma_post: 4.2
    threshold: 0.176
  guidance_kwargs:
    omega: 1
    omega_vent: 0.3
    omega_sept: 2.037
    eta: 0.00780
    smooth_l1_beta: 1.6355
